### ISSUE TITLE
Error while opening Polymake on Mac 

### ISSUE THREAD

**Issue by SidYaj** [polymake/polymake#7]
I am using macOS High Sierra 10.13.6. I am trying to get Polymake running. I downloaded the correct bundle for 10.13. However, I get this error in my Terminal.

===========================================================================

Last login: Wed Mar 10 19:27:03 on ttys000
Siddharths-MacBook-Pro:~ siddharthyajaman$ /Applications/polymake.app/Contents/MacOS/polymake.run ; exit;
Welcome to polymake version 4.3
Copyright (c) 1997-2020
Ewgenij Gawrilow, Michael Joswig, and the polymake team
Technische Universität Berlin, Germany
https://polymake.org

This is free software licensed under GPL; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Loading applications now.../Applications/polymake.app/Contents/MacOS/polymake.start: line 28:   609 Illegal instruction: 4  $ResourcesDir/polymake/bin/polymake "$@"
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

=====================================================================

I am not sure what the problem is. I was getting the same error on my M1 Mac so I decided to try using my old Intel Mac instead.

**Comment by apaffenholz** [comment]
Based on discussions with other users polymake probably currently does not compile on any M1 Mac. And certainly none of the provided binaries will run. We don't have one to test ourselves, so we cannot offer much support here. 

The second problem leading to an "illegal instruction" is caused by some instruction in the binary code of the bundle, that is not/not correctly understood by your intel processor in the other Mac. We haven't seen this problem before, but a search on the net produces surprisingly many pages that report this problem for software compiled on 10.13.X for X less than 6 executed on 10.13.6. Yet, all without a clear solution. 

We may be able to say more if you tell us more about your Mac (processor type, speed, cores, build date of the Mac, version of clang), but I don't have a Mac with 10.13.6 and so cannot reproduce the problem. The official support for 10.13 has ended last year (pretty much after the update from 10.13.5 to 10.13.6), so it might also be hard to still make a fresh installation for testing. 

I would suggest that you either update your Mac to at least 10.14 or try to install via brew. There are instructions for this on our page at [polymake.org](https://polymake.org). If you opt for polymake in version 4.2 then there is a binary for brew available. If you need 4.3, then the brew installation command will do a full source installation. This should finish without any required interaction (though it will take time). If it fails, it will at least produce a more clear error message.

**Comment by benlorenz** [comment]
> Based on discussions with other users polymake probably currently does not compile on any M1 Mac. And certainly none of the provided binaries will run. We don't have one to test ourselves, so we cannot offer much support here.
> 

In fact I do have (remote) access to an M1 Mac, the latest polymake master should compile there and I will have a look if I can make a bundle soon.

**Comment by SidYaj** [comment]
@apaffenholz ,
Here are the details of my old Mac:
MacBook Pro 13" Early 2011
Dual Core i5 2.3 GHz
Clang version 9.1.0

I did try installing it using Homebrew but it threw some errors there as well. My Mac is not upgradable to 10.14. Could you give me more information on installing version 4.2 through brew? Thanks!

**Comment by SidYaj** [comment]
@benlorenz ,
Thank you so much! It would be really helpful to be able to use it on my M1 Mac.

**Comment by SidYaj** [comment]
@apaffenholz @benlorenz I also had another question about the computational power of Polymake. I tried using similar packages in MATLAB and Python (Pycddlib) to convert a 384 by 64 matrix from V representation to H representation. Even after days of running, we got no output from them. Do you think Polymake would be able to handle something like that?

**Comment by apaffenholz** [comment]
Installing polymake in any version on 10.13 via brew is more invovled than I expected, as several packages polymake depends on have dropped support for 10.13. Sorry.

You will have to install those packages individually with brew before you download and install polymake. Here is the list of commands needed. I have tested this on a fresh installation of 10.13.1. I assume it will also work on 10.13.6, but I cannot check this. 

brew tap apaffenholz/polymake
brew install --build-from-source icu4c
brew install --build-from-source boost
brew install --build-from-source ntl
brew install --build-from-source flint
brew install --build-from-source gdbm
brew install --build-from-source mpdecimal
brew install --build-from-source openssl@1.1
brew install --build-from-source readline
brew install --build-from-source sqlite
brew install --build-from-source tcl-tk
brew install --build-from-source python@3.9
brew install --build-from-source ninja
brew install --build-from-source singular
brew install polymake

This will take a while (expect hours), but should give you the latest version 4.3 of polymake. 

I compiled the the polymake bundle with clang 10. This may explain the illegal "instruction error" you encountered, as the newer clang on a slightly newer intel processor has done some optimization that does not work on an older processor (mine is also a Core i5, but from 2013). I don't see a way to fix that. With the dropped support by apple for 10.13 we essentially have to follow and also stop supporting 10.13. 

About your convex hull question:

I assume that 64 is the dimension and 384 is the number of vertices/points? Whether it is still feasible to compute the facets of this polyhedron very much depends on the polyhedron. In general I would not expect that this will work. Note that the number of facets can be expenential in the number of vertices (think of the cross polytope with 2d vertices, but 2^d facets). polymake provides several options to compute the convex hull (some own, some via an interface). Depending on your problem some may work better than others (but note that there is no way to decide this a priori). You can find some hints in our paper 

Assarf, Benjamin; Gawrilow, Ewgenij; Herr, Katrin; Joswig, Michael; Lorenz, Benjamin; Paffenholz, Andreas; Rehn, Thomas. Computing convex hulls and counting integer points with polymake. Math. Program. Comput. 9 

that specifically addresses convex hull computations. 

But I would not expect that any method works without further analysis of the problem and tweaking the algorithms to use additional information on the problem.

**Comment by benlorenz** [comment]
Can you try the following bundle for the Apple M1: https://polymake.org/downloads/polybundle-v4.3-macos-11.2-applem1-perl-5.28.2-v1.dmg

@apaffenholz for some reason it is smaller than the other bundles (300MB instead of 450MB) maybe something is missing? (I used `--without-java` but that was set for 11.1 as well)

**Comment by apaffenholz** [comment]
@benlorenz 

> @apaffenholz for some reason it is smaller than the other bundles (300MB instead of 450MB) maybe something is missing? (I used `--without-java` but that was set for 11.1 as well)

I can spot two things: for some reason in my bundles the temporary build dir of polymake was not removed, so it ended up in the src folder of the bundle (containing the sources to comply with gpl), and that folder is rather large, and openssl is missing. 

The latter may be the same problem as reported for the homebrew formula here:
https://github.com/apaffenholz/homebrew-polymake/issues/2

This should not be difficult to fix, but without any option to test I can only guess the correct solution, and that maybe is not a good approach. 

I don't immediately see anything else missing, maybe shared libraries on M1 are generally smaller (for some time the intel ones bundled 64bit and 32bit code etc, that has stopped, but there may be some overhead left...) or something like this.

**Comment by benlorenz** [comment]
openssl failed to build because I used `-mcpu=generic`, but this seems to disable some aes instructions that openssl needs:
```
building openssl: crypto/aes/aesv8-armx.S:49:2: error: instruction requires: aes
building openssl:  aese v6.16b,v0.16b
```

New build is in progress, openssl did install this time and Net::SSLeay installation also seems to have worked fine.

**Comment by benlorenz** [comment]
New bundle is complete: https://polymake.org/downloads/polybundle-v4.3-macos-11.2-applem1-perl-5.28.2-v1.dmg

I cannot properly test it as I cannot install the app but running the tests directly from the mounted volume looks good:
```
% /Volumes/polybundle/polymake.app/Contents/MacOS/polymake.start --script run_testcases
...
*** All tests successful ***
```

**Comment by SidYaj** [comment]
Thank you both for all your efforts! It is extremely helpful!
